(* ::Package:: *)

(* ::Input:: *)
(*Module[{f,g,a,p,z,u},*)
(*f[t_]={1+Sin[1.3t],Sin[.7t]};*)
(*g[t_]=2{Cos[1.3t],Cos[.7t]};*)
(*a=2.8;*)
(*p[f_,h_]_=ParametricPlot[f[t],{t,0.5,8}m*)
(*PlotStyle->{Hue[0.53,0.5,0.78],Thickness[.01]}];*)
(*z[1]={Thickness[.007], Arrow[f[a], f[a]+f'[a]]};*)
(*z[2]={Thickness[.007], Arrow[g[a], g[a]+g'[a]]};*)
(*z[3]= {Thickness[.007], Arrow[g[a], g*)
(*[a]+f'[a]]};*)
(*]*)
