(* ::Package:: *)

(* ::Input:: *)
(*\[Alpha][t_] := {t, t^2, t^3}*)
(*L[v_] := Sqrt[Simplify[v.v]]*)
(*D[\[Alpha][t], t]*)
(*\[Alpha]'[u]*)
(*L[\[Alpha]'[t]]*)
(**)
(*Clear[\[Alpha], f]*)
(*\[Beta][t_] := \[Alpha][f[t]]*)
(*Table[D[\[Beta][t], {t,k}], {k, 4}]*)
(*ColumnForm[%]*)
(*Do[Print[D[\[Beta][t], {t,k}]], {k,5,6}]*)
(**)
(*\[Alpha][t_] := {Cos[5t], Cos[7t]}*)
(*ParametricPlot[\[Alpha][t]//Evaluate, {t, 1, \[Pi]}, AspectRatio->Automatic]*)
(**)
(*circ[a_][t_] := {a Cos[t],a Sin[t]}*)
(*parabola[a_][t_] := {2a t, a t^2}*)
(*ellipse[a_, b_][t_] := {a Cos[t], b Sin[t]}*)
(*ParametricPlot[ellipse[6, 3][t]//Evaluate, {t, 0, 2 \[Pi]}, AspectRatio->Automatic]*)
(**)



